package vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Productos;
import modelo.ProductosDAO;
import modelo.Validaciones;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author joelr
 */
public class InsertarProductos extends javax.swing.JFrame {

    /**
     * Creates new form InsertarProductos
     */
    List<Productos> listaProductos = new ArrayList<>();
    DefaultTableModel modelo;
    ProductosDAO productosDAO = new ProductosDAO();
    Validaciones val = new Validaciones();

    public InsertarProductos() {
        initComponents();
        setLocationRelativeTo(null);
        productosDAO.ConsultarProveedor(cbxProveedorProducto);
        modelo = (DefaultTableModel) tablaProductos.getModel();
        AutoCompleteDecorator.decorate(cbxProveedorProducto);// Autocompleta al escribir dentro del JComboBox
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        txtCodigoProducto = new javax.swing.JTextField();
        txtDescripcionProducto = new javax.swing.JTextField();
        txtCantidadProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        cbxProveedorProducto = new javax.swing.JComboBox<>();
        btnRegistrarProducto = new javax.swing.JButton();
        btnGuardarySalir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 239, 214));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CÓDIGO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DESCRIPCIÓN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CANTIDAD");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRECIO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PROVEEDOR");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 110, 250, -1));

        btnEliminarProducto.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminarProducto.setText("ELIMINAR PRODUCTO");
        btnEliminarProducto.setToolTipText("Botón Eliminar producto. Seleccione haciendo clic a un producto dentro de la lista para eliminarlo de la lista.");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 250, -1, 50));

        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoProducto.setToolTipText("Se introduce el código de un nuevo producto.");
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyPressed(evt);
            }
        });
        jPanel2.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 200, 35));

        txtDescripcionProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescripcionProducto.setToolTipText("Se introduce la descripción de un nuevo producto.");
        jPanel2.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 300, 35));

        txtCantidadProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidadProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadProducto.setToolTipText("Se introduce la cantidad de un nuevo producto.");
        txtCantidadProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 150, 35));

        txtPrecioProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecioProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioProducto.setToolTipText("Se introduce el precio de un nuevo producto.");
        txtPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 130, 35));

        cbxProveedorProducto.setEditable(true);
        cbxProveedorProducto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbxProveedorProducto.setToolTipText("Se introduce el proveedor de un nuevo producto.");
        jPanel2.add(cbxProveedorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 140, 250, 35));

        btnRegistrarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarProducto.setText("INSERTAR");
        btnRegistrarProducto.setToolTipText("Boton Insertar. Haga clic para añadir el producto a la tabla.");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 140, 150, 35));

        btnGuardarySalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarySalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar-el-archivo.png"))); // NOI18N
        btnGuardarySalir.setText("GUARDAR Y SALIR");
        btnGuardarySalir.setToolTipText("Botón de Guardar y Salir. Haga clic en este boton para guardar todos los productos que esten en la tabla y cerrar la ventana.");
        btnGuardarySalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarySalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarySalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 50));

        tablaProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CÓDIGO", "DESCRIPCIÓN", "CANTIDAD", "PRECIO", "PROVEEDOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.setToolTipText("Tabla con los productos a añadir.");
        tablaProductos.setRowHeight(30);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaProductos);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1920, 685));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        int fila = tablaProductos.getSelectedRow();
        if (fila >= 0) {
            modelo.removeRow(fila);
            listaProductos.remove(fila);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para eliminar");
        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void txtCodigoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyPressed

    }//GEN-LAST:event_txtCodigoProductoKeyPressed

    private void txtCantidadProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadProductoKeyPressed

    }//GEN-LAST:event_txtCantidadProductoKeyPressed

    private void txtCantidadProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadProductoKeyTyped
        // Valida que solo se ingresen números
        val.soloNumeros(evt);
    }//GEN-LAST:event_txtCantidadProductoKeyTyped

    private void txtPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProductoKeyTyped
        // Valida que solo se ingresen números y decimales
        val.soloNumerosDecimales(evt, txtPrecioProducto);
    }//GEN-LAST:event_txtPrecioProductoKeyTyped

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        agregarProducto();
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked

    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnGuardarySalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarySalirActionPerformed
        // Verifica si la lista de productos no está vacía
        if (!listaProductos.isEmpty()) {
            // Recorre la lista
            for (Productos producto : listaProductos) {
                productosDAO.RegistarProducto(producto);// Registra el producto
            }
            JOptionPane.showMessageDialog(this, "Productos guardados exitosamente");
            dispose();// Cierra la ventana actual
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos para guardar");
        }
    }//GEN-LAST:event_btnGuardarySalirActionPerformed
    private void agregarProducto() {
        try {
            // Obtiene los datos ingresados por el usuario en los campos de texto y combo box
            String codigo = txtCodigoProducto.getText();
            String nombre = txtDescripcionProducto.getText();
            int cantidad = Integer.parseInt(txtCantidadProducto.getText());
            double precio = Double.parseDouble(txtPrecioProducto.getText());
            String proveedorProducto = (String) cbxProveedorProducto.getSelectedItem();
            
            // Crea un nuevo objeto Producto con los datos obtenidos
            Productos producto = new Productos(0, codigo, nombre, cantidad, proveedorProducto, cantidad, precio);
            // Añade el producto a la lista de productos
            listaProductos.add(producto);

            Object[] fila = new Object[6];
            fila[0] = listaProductos.size();  // ID ficticio basado en el tamaño de la lista
            fila[1] = producto.getCodigo();
            fila[2] = producto.getNombre();
            fila[3] = producto.getStock();
            fila[4] = producto.getPrecio();
            fila[5] = producto.getProveedorProducto();

            // Añade la fila al modelo de la tabla
            modelo.addRow(fila);

            limpiarCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifique que los campos de cantidad y precio sean números válidos.");
        }
    }

    private void limpiarCampos() {
        txtCodigoProducto.setText("");
        txtDescripcionProducto.setText("");
        txtCantidadProducto.setText("");
        txtPrecioProducto.setText("");
        txtCantidadProducto.setText("");
        cbxProveedorProducto.setSelectedItem(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardarySalir;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JComboBox<String> cbxProveedorProducto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
